language: julia
os:
  - linux
  - osx
  - windows
arch:
  - x86
  - x64
  - arm64
julia:
  - 1.3
matrix:
  exclude:
    - os: osx
      arch: arm64
    - os: osx
      arch: x86
    - os: windows
      arch: arm64
notifications:
  email: false
